
#!/usr/bin/env python3
"""AdditDownloader CLI.

This tool keeps a tiny local registry of app names and download URLs, downloads
registered apps, and can generate a Homebrew cask scaffold for GUI apps.

Command aliases:
- add / mk
- download / dwnd
- install-window / window_cask
"""

from __future__ import annotations

import argparse
import json
import shutil
import urllib.parse
import urllib.request
from pathlib import Path


REGISTRY_FILE = Path("registry.json")


def load_registry() -> dict[str, dict[str, str]]:
      if REGISTRY_FILE.exists():
                try:
                              with REGISTRY_FILE.open("r", encoding="utf-8") as file:
                                                data = json.load(file)
                                            if isinstance(data, dict):
                                                              return data
                except json.JSONDecodeError:
                              pass
                      return {}


def save_registry(data: dict[str, dict[str, str]]) -> None:
      with REGISTRY_FILE.open("w", encoding="utf-8") as file:
                json.dump(data, file, indent=4, sort_keys=True)
                file.write("\n")


def add_app(name: str, url: str) -> None:
      registry = load_registry()
      registry[name] = {"url": url}
      save_registry(registry)
      print(f" Successfully added '{name}' to the AdditDownloader registry!")


def _filename_from_url(url: str, fallback: str) -> str:
      parsed = urllib.parse.urlparse(url)
      filename = Path(parsed.path).name
      if filename:
                return filename
            return fallback


def _download_to_path(url: str, destination: Path) -> None:
      destination.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(url) as response, destination.open("wb") as file:
              shutil.copyfileobj(response, file)


def download_app(name: str, destination: str | None = None) -> None:
      registry = load_registry()
    if name not in registry:
              print(f" Error: '{name}' not found. Please add it first.")
              return

    url = registry[name]["url"]
    target_dir = Path(destination) if destination else Path.cwd()
    target_name = _filename_from_url(url, name)
    target_path = target_dir / target_name

    print(f" Downloading '{name}' from {url}...")
    try:
              _download_to_path(url, target_path)
except Exception as exc:  # pragma: no cover - user-facing error path
        print(f" Download failed: {exc}")
        return

    print(f" Download complete: {target_path}")


def _slugify(name: str) -> str:
      slug = []
    for char in name.lower():
              if char.isalnum():
                            slug.append(char)
elif char in {" ", "-", "_", "."}:
            slug.append("-")
    result = "".join(slug).strip("-")
    return result or "app"


def install_window(name: str, output_dir: str | None = None) -> None:
      registry = load_registry()
    if name not in registry:
              print(f" Error: '{name}' not found. Please add it first.")
              return

    url = registry[name]["url"]
    cask_dir = Path(output_dir) if output_dir else Path("Casks")
    cask_dir.mkdir(parents=True, exist_ok=True)
    cask_path = cask_dir / f"{_slugify(name)}.rb"

    template = f'''cask "{_slugify(name)}" do
      version "latest"
        sha256 :no_check
          url "{url}"
            name "{name}"
              desc "Window cask scaffold generated by AdditDownloader"
                homepage "https://github.com/marzio-cloud/AdditDownloader"

                  app "{name}.app"
                  end
                  '''

    cask_path.write_text(template, encoding="utf-8")
    print(f" Generated window cask scaffold at {cask_path}")


def build_parser() -> argparse.ArgumentParser:
      parser = argparse.ArgumentParser(
          description="AdditDownloader - manage a local app registry, downloads, and window cask scaffolds."
)
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    parser_add = subparsers.add_parser("add", help="Add a new app to the registry")
    parser_add.add_argument("name", help="The name of the app")
    parser_add.add_argument("url", help="The download URL for the app")

    parser_mk = subparsers.add_parser("mk", help="Alias for add")
    parser_mk.add_argument("name", help="The name of the app")
    parser_mk.add_argument("url", help="The download URL for the app")

    parser_download = subparsers.add_parser("download", help="Download an app")
    parser_download.add_argument("name", help="The name of the app to download")
    parser_download.add_argument(
              "--dest",
              default=None,
              help="Optional destination directory for the downloaded file",
    )

    parser_dwnd = subparsers.add_parser("dwnd", help="Alias for download")
    parser_dwnd.add_argument("name", help="The name of the app to download")
    parser_dwnd.add_argument(
              "--dest",
              default=None,
              help="Optional destination directory for the downloaded file",
    )

    parser_install = subparsers.add_parser(
              "install-window", help="Generate a Homebrew cask scaffold for a windowed app"
    )
    parser_install.add_argument("name", help="The name of the app to generate a cask for")
    parser_install.add_argument(
              "--output",
              default=None,
              help="Optional directory to write the cask file into",
    )

    parser_window_cask = subparsers.add_parser(
              "window_cask", help="Alias for install-window"
    )
    parser_window_cask.add_argument("name", help="The name of the app to generate a cask for")
    parser_window_cask.add_argument(
              "--output",
              default=None,
              help="Optional directory to write the cask file into",
    )

    return parser


def main() -> None:
      parser = build_parser()
      args = parser.parse_args()

    if args.command in {"add", "mk"}:
              add_app(args.name, args.url)
elif args.command in {"download", "dwnd"}:
          download_app(args.name, args.dest)
elif args.command in {"install-window", "window_cask"}:
          install_window(args.name, args.output)
else:
          parser.print_help()


if __name__ == "__main__":
      main()
  
